import { writeFileSync } from "fs";
import { join } from "path";

/**
 * Feedback wrapper script generator.
 *
 * Produces a shell script that wraps each configured feedback command:
 * - On exit 0: prints a 1-line summary (command name + wall-clock duration).
 * - On non-zero exit: prints full stdout/stderr so the agent can diagnose.
 * - On timeout: kills the child process and prints partial output.
 *
 * The generated script is written to the WIP slug directory (pipeline
 * state, e.g. `~/.ralphai/repos/<id>/pipeline/in-progress/<slug>/`)
 * by the runner before the iteration loop starts. This keeps the
 * wrapper out of the user's worktree so it doesn't appear as an
 * untracked file in `git status`.
 *
 * `writeFeedbackWrapper` handles writing the generated script to disk.
 * `generateFeedbackWrapper` is a pure function — no I/O.
 */

/** Filename of the generated wrapper script. */
export const FEEDBACK_WRAPPER_FILENAME = "_ralphai_feedback.sh";

/** Default timeout in seconds for each wrapped command. */
export const DEFAULT_TIMEOUT_SECONDS = 300;

/**
 * Parse a comma-separated feedback commands string into an array of
 * individual command strings, trimming whitespace and dropping empties.
 *
 * @param feedbackCommands - Comma-separated string (e.g. `"bun test, bun run lint"`).
 * @returns Array of non-empty command strings.
 */
export function parseFeedbackCommands(feedbackCommands: string): string[] {
  if (!feedbackCommands.trim()) return [];
  return feedbackCommands
    .split(",")
    .map((c) => c.trim())
    .filter(Boolean);
}

/**
 * Generate a shell script that runs each feedback command sequentially,
 * printing a concise summary on success and full output on failure.
 *
 * @param commands - Array of shell commands to wrap (e.g. `["bun test", "bun run lint"]`).
 * @param timeoutSeconds - Per-command timeout in seconds. Defaults to 300 (5 minutes).
 * @returns The complete shell script content as a string.
 */
export function generateFeedbackWrapper(
  commands: string[],
  timeoutSeconds: number = DEFAULT_TIMEOUT_SECONDS,
): string {
  if (commands.length === 0) {
    return generateEmptyWrapper();
  }

  const total = commands.length;
  const commandBlocks = commands
    .map((cmd, i) => `run_command ${escapeForShell(cmd)} ${i + 1} ${total}`)
    .join("\n");

  return `#!/usr/bin/env bash
# Auto-generated by ralphai — do not edit manually.
# This script wraps feedback commands to provide concise output on success
# and full diagnostic output on failure. Regenerated on each run.
set -o pipefail

TIMEOUT_SECONDS=${timeoutSeconds}
FINAL_EXIT=0

run_command() {
  local cmd="\$1"
  local index="\$2"
  local total="\$3"
  local tmpfile
  tmpfile=\$(mktemp)

  local start_time
  start_time=\$(date +%s)

  # Run with timeout, capturing all output
  local exit_code=0
  if command -v timeout >/dev/null 2>&1; then
    timeout --signal=KILL "\${TIMEOUT_SECONDS}" bash -c "\${cmd}" >"\${tmpfile}" 2>&1
    exit_code=\$?
  else
    # macOS fallback: no coreutils timeout — run without timeout guard
    bash -c "\${cmd}" >"\${tmpfile}" 2>&1
    exit_code=\$?
  fi

  local end_time
  end_time=\$(date +%s)
  local duration=$(( end_time - start_time ))

  if [ \${exit_code} -eq 137 ] || [ \${exit_code} -eq 124 ]; then
    # Killed by timeout (137 = SIGKILL, 124 = timeout exit code)
    echo "[\${index}/\${total}] TIMEOUT after \${duration}s: \${cmd}"
    echo "--- partial output ---"
    cat "\${tmpfile}"
    echo "--- end partial output ---"
    FINAL_EXIT=1
  elif [ \${exit_code} -ne 0 ]; then
    echo "[\${index}/\${total}] FAIL (exit \${exit_code}) after \${duration}s: \${cmd}"
    cat "\${tmpfile}"
    FINAL_EXIT=\${exit_code}
  else
    echo "[\${index}/\${total}] OK (\${duration}s): \${cmd}"
  fi

  rm -f "\${tmpfile}"
  return \${exit_code}
}

${commandBlocks}

exit \${FINAL_EXIT}
`;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Generate the wrapper when no commands are configured.
 * Prints a message and exits 0.
 */
function generateEmptyWrapper(): string {
  return `#!/usr/bin/env bash
# Auto-generated by ralphai — do not edit manually.
# No feedback commands configured.
echo "No feedback commands configured."
exit 0
`;
}

/**
 * Escape a command string for safe embedding in a shell script as a
 * single-quoted argument. Single quotes within the command are escaped
 * using the `'\''` idiom (end quote, escaped quote, start quote).
 */
function escapeForShell(cmd: string): string {
  return `'${cmd.replace(/'/g, "'\\''")}'`;
}

// ---------------------------------------------------------------------------
// File I/O
// ---------------------------------------------------------------------------

/**
 * Write the feedback wrapper script to the given directory.
 * Typically called with the WIP slug directory so the script stays
 * out of the user's worktree (no untracked-file noise in git status).
 * Skipped on Windows (process.platform === "win32") and when no
 * feedback commands are configured.
 */
export function writeFeedbackWrapper(
  targetDir: string,
  feedbackCommands?: string[],
): void {
  if (process.platform === "win32") return;
  if (!feedbackCommands || feedbackCommands.length === 0) return;

  const script = generateFeedbackWrapper(feedbackCommands);
  const wrapperPath = join(targetDir, FEEDBACK_WRAPPER_FILENAME);
  writeFileSync(wrapperPath, script, { mode: 0o755 });
}
