import { execFileSync } from "child_process";
import { describe, expect, it } from "vitest";
import { join } from "path";

describe("hello-ralphai sample script", () => {
  it("prints the greeting and metadata", () => {
    const scriptPath = join(import.meta.dirname, "..", "hello-ralphai.mjs");
    const output = execFileSync("node", [scriptPath], {
      encoding: "utf8",
    })
      .trim()
      .split("\n");

    expect(output[0]).toContain("Ralphai");
    expect(output[0]).toBe("Hello from Ralphai!");
    expect(output[1]).toBe("This sample script was generated by Ralphai.");
    expect(output[2]).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);
  });
});
